name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Set up Go 1.22
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      # Install Revive linter via action
      - name: Revive Action
        uses: morphy2k/revive-action@v2.4.1

      # Install Staticcheck manually to respect Go 1.22
      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      # Run Staticcheck
      - name: Run Staticcheck
        run: staticcheck ./...

      # Download modules and install gotestsum
      - name: Build
        run: |
          go mod download
          go install gotest.tools/gotestsum@latest
          go build -v ./...

      # Run tests with gotestsum and produce JUnit XML
      - name: Test
        run: |
          gotestsum --format=standard-verbose --junitfile=junit.xml -- ./...

      # Publish test report to GitHub checks
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true
