name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Revive Action
        uses: morphy2k/revive-action@v2.4.1

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0

      - name: Build
        run: |
          go mod download
          go install gotest.tools/gotestsum@latest
          go build -v ./...

      - name: Test
        run: |
          gotestsum --format=standard-verbose --junitfile=junit.xml -- ./...

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true
